# Generated by Django 4.1 on 2023-08-14 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmodel',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='images/%y/%m/%d'),
        ),
    ]
